<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:tns="http://Services/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" name="RequesterService" targetNamespace="http://Services/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="http://localhost:8090/?xsd=1" namespace="http://Services/" />
    </xsd:schema>
  </types>
  <message name="SubmitMouse">
    <part name="parameters" element="tns:SubmitMouse" />
  </message>
  <message name="SubmitMouseResponse">
    <part name="parameters" element="tns:SubmitMouseResponse" />
  </message>
  <portType name="Requester">
    <operation name="SubmitMouse">
      <input wsam:Action="http://Services/Requester/SubmitMouseRequest" message="tns:SubmitMouse" />
      <output wsam:Action="http://Services/Requester/SubmitMouseResponse" message="tns:SubmitMouseResponse" />
    </operation>
  </portType>
  <binding name="RequesterPortBinding" type="tns:Requester">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="SubmitMouse">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="RequesterService">
    <port name="RequesterPort" binding="tns:RequesterPortBinding">
      <soap:address location="http://localhost:8090/" />
    </port>
  </service>
</definitions>